name: build
on:
  push:
    branches: [ master ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter action
        uses: subosito/flutter-action@v2.3.0
        with:
          flutter-version: 2.10.3
          channel: stable
      - name: Build apk
        run:
          flutter pub get
          flutter format --set-exit-if-changed
          flutter analyze
          flutter test
          flutter build apk --debug
