name: build
on:
  push:
    branches: [ master ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed
          flutter analyze
          flutter test
          flutter build apk --debug
