name: build
on:
  push:
    branches: [ master ]
jobs:
  build-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Flutter action
      # You may pin to the exact commit or the version.
      # uses: subosito/flutter-action@5e1529bc12adae5b26f30f0a4046ac743d6f0c5d
        uses: subosito/flutter-action@v2.3.0
        with:
          # The Flutter version to make available on the path
          flutter-version: 2.10.3
          # The Flutter build release channel
          channel: stable
      - name: Build apk
        run: |
          flutter pub get
          flutter format --set-exit-if-changed
          flutter analyze
          flutter test
          flutter build apk --debug
